### PR TITLE
some cherry-picks: warnings, reveal option, surface in gps

### PR DESCRIPTION
**Pull request by winex**
@bahrmichael , this is **low priority**
when you have spare time please review these cherry-picks one-by-one from latest [winex:rbgen](https://github.com/winex/factorio-tycoon/tree/rbgen)

i thought some of these commits could be merged early (for translations, options, etc) to minimize later PR(s). so, please select:
1. which ones you can accept at this stage
2. which should i remove from here
3. what text/description needs to be changed, reworded, etc...

### tests
i've done some real tests with mods to see how things work and how we should handle some new cases like:
- actually supporting multi-surface with `space-exploration` in `rbgen`
- more forces with `CitiesOfEarth3`... _-- needs more work_

as i have many saves with different **dev** states now, i always do my tests against all of them.
for ex: `fix: migrate old TagsQueue entries` that were w/o multi-surface are to be found only in our **dev saves**. it's more like an example code, but didn't do any harm.

### migrations spam
i suppose all old migrations should be dropped at some later point when we get more stable like `v0.8` or even `v0.9.9`. we can inform old-save-users that some previous version is needed to be ran **first** to correctly upgrade if players really want it that way.

thanks!

### CODE REVIEW

**Comment by bahrmichael** [comment]
> i suppose all old migrations should be dropped at some later point when we get more stable like v0.8 or even v0.9.9. we can inform old-save-users that some previous version is needed to be ran first to correctly upgrade if players really want it that way.

Agreed, I'm fine with deprecating older migrations. Maybe removing migrations that are older than 6 months is a good start?

**Comment by bahrmichael** [comment]
> as i have many saves with different dev states now, i always do my tests against all of them.

That's awesome! The next version will probably be a breaking change, so don't worry about that too much.

**Comment by bahrmichael** [comment]
With https://github.com/bahrmichael/factorio-tycoon/pull/316/commits/f6cbabe762a8f54603a4cd1ad60bbbdad839b9ef I'm rather leaning towards disabling the reveal by default. Do you have strong reasons for enabling it by default?

**Comment by bahrmichael** [comment]
With https://github.com/bahrmichael/factorio-tycoon/pull/316/commits/03910a6760eae2d299a320063f6872ad43c15ee6 I would much rather keep the longer variables, and not reuse them for different objects. Is it okay if we drop that change?

**Comment by bahrmichael** [comment]
I'm happy with the other changes :) Will wait on your feedback for the comments above @winex.

**Comment by winex** [comment]
> With [03910a6](https://github.com/bahrmichael/factorio-tycoon/commit/03910a6760eae2d299a320063f6872ad43c15ee6) I would much rather keep the longer variables, and not reuse them for different objects. Is it okay if we drop that change?

yep, of course. i just added that var in some earlier PR on top of this `if`-blocks and changed some so it doesn't look that ugly for return checks being on random columns inside such condition checks.
dropping...

> With [f6cbabe](https://github.com/bahrmichael/factorio-tycoon/commit/f6cbabe762a8f54603a4cd1ad60bbbdad839b9ef) I'm rather leaning towards disabling the reveal by default. Do you have strong reasons for enabling it by default?

nope, it just helped to find those when playtesting.
changing...

**Pull request merged**
