### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by bahrmichael**

### CODE REVIEW

**Comment by winex** [comment]
hmm, `Luacheck` action shouldn't be running on such PRs.
it's because `on: [pull_request]`, but idk what actually to suggest :(

is there smth like `from_branch: l10n_main`?

**Comment by bahrmichael** [comment]
@winex Why do you think it shouldn't run here? The changes in this PR are something we should validate.

**Comment by bahrmichael** [comment]
What you're asking for is possible with

```yaml
on:
  pull_request:
    branches:
      - l10n_main
```

**Comment by winex** [comment]
> @winex Why do you think it shouldn't run here? The changes in this PR are something we should validate.

these are translations and they are `.cfg` files (not `.lua`), so **`luacheck`** probably does nothing useful here
well, unless crowdin updates could change some `.lua` files...

**Comment by bahrmichael** [comment]
You're right! I confused the workflows, thanks for clearing that up

**Pull request merged**
